name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: jvmTest
            os: ubuntu-latest
          - target: jsNodeTest
            os: ubuntu-latest
          - target: linuxX64Test
            os: ubuntu-latest
          - target: macosArm64Test
            os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v2
    - uses: actions/cache@v4
      with:
        path: |
          ~/.konan
        key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
    - name: Install curl
      uses: awalsh128/cache-apt-pkgs-action@v1
      if: runner.os == 'Linux'
      with:
       packages: libcurl4-gnutls-dev
       version: 1.0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: ./gradlew :integration-tests:${{ matrix.target }}
